name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login uhub.service.ucloud.cn -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF})
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag uhub.service.ucloud.cn/alpha_supsys/laya-demo-game:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push uhub.service.ucloud.cn/alpha_supsys/laya-demo-game:${{steps.vars.outputs.tag}}
